import type { BuilderState } from "./builder";

type DemoPreset = {
  id: string;
  name: string;
  subtitle: string;
  data: Partial<BuilderState>;
};

export const DEMO_PRESETS: DemoPreset[] = [
  {
    id: "wizard",
    name: "Wizard academico",
    subtitle: "Control y conocimiento",
    data: {
      characterName: "Aelthar Voss",
      playerName: "Demo",
      alignment: "Neutral Bueno",
      raceId: "human",
      classId: "wizard",
      backgroundId: "sage",
      featId: "magic-initiate",
      weaponId: "quarterstaff",
      armorId: "mage-armor",
      extraEquipmentText: "spellbook\ncomponent-pouch\nscholar-pack",
      proficienciesText: "Arcana\nHistory\nInvestigation",
      languagesText: "Common\nDraconic\nElvish",
      cantripsText: "Mage Hand\nPrestidigitation\nRay of Frost",
      spellsText: "Nv1: Mage Armor\nNv2: Misty Step\nNv3: Fireball\nNv3: Counterspell",
      featuresText: "Arcane Recovery",
      level: 5,
      str: 8,
      dex: 14,
      con: 12,
      int: 18,
      wis: 13,
      cha: 10,
      trait: "Analiza cada escena como si fuera un problema arcano esperando resolverse.",
      ideal: "El conocimiento compartido puede cambiar el destino de un reino.",
      bond: "Busca una biblioteca perdida vinculada a la desaparicion de su maestra.",
      flaw: "Puede subestimar riesgos sociales cuando una pista intelectual aparece.",
      notes: "Especialista en control, defensa y lectura de reliquias.",
    },
  },
  {
    id: "rogue",
    name: "Rogue urbana",
    subtitle: "Sigilo y precision",
    data: {
      characterName: "Nyx Vale",
      playerName: "Demo",
      alignment: "Caotico Bueno",
      raceId: "human",
      classId: "rogue",
      backgroundId: "criminal",
      featId: "alert",
      weaponId: "rapier",
      armorId: "leather",
      extraEquipmentText: "thieves-tools\ngrappling-hook\ndark-cloak",
      proficienciesText: "Stealth\nAcrobatics\nInvestigation\nThieves' Tools",
      languagesText: "Common\nThieves' Cant",
      cantripsText: "",
      spellsText: "",
      featuresText: "Sneak Attack\nCunning Action",
      level: 5,
      str: 10,
      dex: 18,
      con: 13,
      int: 14,
      wis: 12,
      cha: 14,
      trait: "Siempre encuentra una salida, incluso cuando nadie mas la ve.",
      ideal: "La libertad vale mas que cualquier juramento vacio.",
      bond: "Protege a su antigua red de informantes de una banda rival.",
      flaw: "Le cuesta confiar en figuras de autoridad.",
      notes: "Build de movilidad, infiltracion y dano explosivo en un solo turno.",
    },
  },
  {
    id: "cleric",
    name: "Cleric de soporte",
    subtitle: "Defensa y curacion",
    data: {
      characterName: "Seren Hal",
      playerName: "Demo",
      alignment: "Legal Bueno",
      raceId: "human",
      classId: "cleric",
      backgroundId: "acolyte",
      featId: "healer",
      weaponId: "mace",
      armorId: "chain-shirt",
      extraEquipmentText: "holy-symbol\nhealers-kit\nprayer-book",
      proficienciesText: "Insight\nMedicine\nReligion",
      languagesText: "Common\nCelestial",
      cantripsText: "Guidance\nSacred Flame\nSpare the Dying",
      spellsText: "Nv1: Bless\nNv1: Healing Word\nNv2: Spiritual Weapon",
      featuresText: "Channel Divinity",
      level: 5,
      str: 12,
      dex: 10,
      con: 14,
      int: 11,
      wis: 18,
      cha: 13,
      trait: "Su presencia calma al grupo incluso en el peor momento.",
      ideal: "El poder solo tiene sentido si protege a otros.",
      bond: "Sirve a un santuario que resiste el avance de fuerzas oscuras.",
      flaw: "Carga con culpas viejas y le cuesta delegar decisiones.",
      notes: "Perfil orientado a soporte, estabilidad del grupo y control del frente.",
    },
  },
];
